Repository pda5th-TheOne/backend, pull requests merged in 2024-11, with the labels that each got.

#3 RestTemplate 및 Swagger 설정 추가
  build.gradle
  src/main/java/pda5th/backend/theOne/config/RestTemplateConfig.java
  src/main/java/pda5th/backend/theOne/config/SwaggerConfig.java
Labels: 환경설정

#4 도커 및 CI/CD 파이프라인 구축 환경설정
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 환경설정

#6 deploy.yml 오류 수정
  .github/workflows/deploy.yml
Labels: bug

#7 GitHub Actions에서 환경 변수 직접 전달 방식으로 배포 자동화 개선
  .github/workflows/deploy.yml
Labels: bug

#8 EC2 배포 워크플로우 환경 변수 및 경로 설정 개선
  .github/workflows/deploy.yml
Labels: bug

#9 EC2 배포 시 SSH 키 및 호스트 키 검증 오류 해결
  .github/workflows/deploy.yml
Labels: bug

#10 EC2 배포 워크플로우에서 SSH 세션 중복 제거 및 경로 설정 최적화
  .github/workflows/deploy.yml
Labels: bug

#12 Spring Security와 JWT를 활용한 인증/인가 기능 구현 및 Docker 환경 개선
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/pda5th/backend/theOne/common/jwt/filter/JwtRequestFilter.java
  src/main/java/pda5th/backend/theOne/common/jwt/util/JwtUtil.java
  src/main/java/pda5th/backend/theOne/common/security/CustomUserDetailsService.java
  src/main/java/pda5th/backend/theOne/common/security/UserPrincipal.java
  src/main/java/pda5th/backend/theOne/config/SecurityConfig.java
  src/main/java/pda5th/backend/theOne/controller/AuthController.java
  src/main/java/pda5th/backend/theOne/dto/AuthRequest.java
  src/main/java/pda5th/backend/theOne/dto/AuthResponse.java
  src/main/java/pda5th/backend/theOne/entity/Provider.java
  src/main/java/pda5th/backend/theOne/entity/Role.java
  src/main/java/pda5th/backend/theOne/entity/User.java
  src/main/java/pda5th/backend/theOne/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 버그수정, 구현

#14 데이터베이스 엔티티 및 관계 구현 PR
  src/main/java/pda5th/backend/theOne/entity/DailyBoard.java
  src/main/java/pda5th/backend/theOne/entity/HoneyGoals.java
  src/main/java/pda5th/backend/theOne/entity/HoneyUsers.java
  src/main/java/pda5th/backend/theOne/entity/Practice.java
  src/main/java/pda5th/backend/theOne/entity/Question.java
  src/main/java/pda5th/backend/theOne/entity/Reply.java
  src/main/java/pda5th/backend/theOne/entity/TIL.java
  src/main/java/pda5th/backend/theOne/entity/UsersPractices.java
Labels: 구현

#16 인증 방식 변경에 따른 유저 테이블 수정 및 회원가입 API 구현
  src/main/java/pda5th/backend/theOne/common/security/UserPrincipal.java
  src/main/java/pda5th/backend/theOne/config/SecurityConfig.java
  src/main/java/pda5th/backend/theOne/controller/UserController.java
  src/main/java/pda5th/backend/theOne/dto/SignUpRequest.java
  src/main/java/pda5th/backend/theOne/entity/Provider.java
  src/main/java/pda5th/backend/theOne/entity/User.java
  src/main/java/pda5th/backend/theOne/service/UserService.java
Labels: 버그수정, 구현

#19 Feat/#18 mainpage
  src/main/java/pda5th/backend/theOne/controller/DailyBoardController.java
  src/main/java/pda5th/backend/theOne/dto/DailyBoardCreateRequest.java
  src/main/java/pda5th/backend/theOne/dto/DailyBoardDetails.java
  src/main/java/pda5th/backend/theOne/repository/DailyBoardRepository.java
  src/main/java/pda5th/backend/theOne/repository/PracticeRepository.java
  src/main/java/pda5th/backend/theOne/repository/QuestionRepository.java
  src/main/java/pda5th/backend/theOne/repository/TILRepository.java
  src/main/java/pda5th/backend/theOne/service/DailyBoardService.java
Labels: 구현

#21 Docker 네트워크 및 CORS 설정 추가
  docker-compose.yml
  src/main/java/pda5th/backend/theOne/config/SecurityConfig.java
Labels: 버그수정

#22 전체 실습 상세 조회 API 구현
  src/main/java/pda5th/backend/theOne/controller/PracticeController.java
  src/main/java/pda5th/backend/theOne/dto/PracticeResponseDto.java
  src/main/java/pda5th/backend/theOne/repository/UsersPracticesRepository.java
  src/main/java/pda5th/backend/theOne/service/PracticeService.java
Labels: 구현

#29 타이머 기능 구현을 위한 Server-Sent Events (SSE) 도입
  src/main/java/pda5th/backend/theOne/TheOneApplication.java
  src/main/java/pda5th/backend/theOne/config/SecurityConfig.java
  src/main/java/pda5th/backend/theOne/controller/TimerController.java
  src/main/java/pda5th/backend/theOne/dto/TimerRequest.java
  src/main/java/pda5th/backend/theOne/dto/TimerResponse.java
Labels: 구현

#31 JWT 인증 및 질문 큐 SSE 구현
  src/main/java/pda5th/backend/theOne/config/SecurityConfig.java
  src/main/java/pda5th/backend/theOne/controller/AuthController.java
  src/main/java/pda5th/backend/theOne/controller/QuestionQueueController.java
  src/main/java/pda5th/backend/theOne/dto/UserInfoResponse.java
Labels: 구현

#38 실습 상세 페이지에서 발생한 두 가지 주요 문제 해결
  src/main/java/pda5th/backend/theOne/controller/PracticeController.java
  src/main/java/pda5th/backend/theOne/dto/PracticeUpdateRequest.java
  src/main/java/pda5th/backend/theOne/entity/UsersPractices.java
Labels: 버그수정, 구현

#42 Feat/#18 main page 1
  src/main/java/pda5th/backend/theOne/entity/DailyBoard.java
  src/main/java/pda5th/backend/theOne/entity/Practice.java
  src/main/java/pda5th/backend/theOne/entity/Question.java
  src/main/java/pda5th/backend/theOne/entity/TIL.java
  src/main/java/pda5th/backend/theOne/repository/PracticeRepository.java
  src/main/java/pda5th/backend/theOne/repository/QuestionRepository.java
  src/main/java/pda5th/backend/theOne/repository/TILRepository.java
  src/main/java/pda5th/backend/theOne/service/DailyBoardService.java
Labels: 구현

#41 Feat/#23 Implement TIL CRUD API
  src/main/java/pda5th/backend/theOne/controller/TILController.java
  src/main/java/pda5th/backend/theOne/repository/TILRepository.java
  src/main/java/pda5th/backend/theOne/service/TILService.java
Labels: 구현

#44 DTO 변환으로 순환 참조 문제 해결
  src/main/java/pda5th/backend/theOne/dto/DailyBoardDetails.java
  src/main/java/pda5th/backend/theOne/service/DailyBoardService.java
Labels: 버그수정
